/*
LAZA SQL Server POC - database creation
APPROVAL REQUIRED BEFORE EXECUTION.
*/
USE [master];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF DB_ID(N'LAZA_DATA_PLATFORM_DEV') IS NOT NULL
    THROW 51001, 'Database LAZA_DATA_PLATFORM_DEV already exists. Stop and review; this script will not modify it.', 1;

EXEC(N'CREATE DATABASE [LAZA_DATA_PLATFORM_DEV];');

ALTER DATABASE [LAZA_DATA_PLATFORM_DEV] SET RECOVERY SIMPLE;
ALTER DATABASE [LAZA_DATA_PLATFORM_DEV] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [LAZA_DATA_PLATFORM_DEV] SET AUTO_CLOSE OFF;
ALTER DATABASE [LAZA_DATA_PLATFORM_DEV] SET AUTO_SHRINK OFF;
ALTER DATABASE [LAZA_DATA_PLATFORM_DEV] SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;

SELECT
    name,
    state_desc,
    recovery_model_desc,
    compatibility_level,
    is_read_committed_snapshot_on
FROM sys.databases
WHERE name = N'LAZA_DATA_PLATFORM_DEV';
GO
